### ISSUE TITLE
遇到一个小问题，在不同的电脑上运行可能会出现PyQt6.QtWidgets cannot import type 'P���' from PyQt6.QtCore

### ISSUE THREAD

**Issue by MasterBeard** [zimolab/PyGUIAdapter#1]
我在自己的电脑上可以运行例子中的：
from pyguiadapter.adapter.adapter import GUIAdapter

gui_adapter = GUIAdapter()
gui_adapter.add(create_file)
但是在公司的电脑上就出现了问题
![image](https://github.com/zimolab/PyGUIAdapter/assets/35285952/3e204926-f4cb-4e76-92f9-35e1de6bb0ed)

**Comment by zimolab** [comment]
感觉像是环境的问题，出问题的代码行是'from PyQt6.Qtwidgets import QApplication, QMessageBox'，按理说这个导入应该不会有什么问题，能否poetry show看一下当前依赖信息。

**Comment by zimolab** [comment]
另外，为什么会出现乱码'P���'呢？可能是编码的问题？可以检查一下编码是GBK还是UTF-8。

**Comment by MasterBeard** [comment]
搞定了，是因为之前我已经装过PyQt6这个package了，可能是我之前装的版本不是最新或者别的原因，我重装了这个PyQt6，退出之后重新在python里面运行就可以了。

**Comment by MasterBeard** [comment]
但又碰见了另外的一个问题就是
 """
    这是一个演示程序，用于演示<b>PyGUIAdapter</b>的功能，这段文字会被提取为函数的Document并显示在界面上。

    :param path: <b>生成文件的保存的目录，若为空则保存到当前路径下</b>
    :param filename: <b>生成文件的文件名称。注意：<font color=red>不可为空！</font></b>
    :param content: <b>生成文件的内容</b>
    :param overwrite:
    :return:

    @widgets
    [path]
    widget_class="DirPathEdit"
    label="保存路径"
    button_text="选择目录"
    placeholder="选择文件保存的目录"

    [filename]
    label="文件名"
    placeholder="生成文件的名称"
    clear_button=true

    [content]
    widget_class="PlainTextEdit"
    label="文件内容"
    placeholder="生成文件的内容"

    [overwrite]
    label=""
    text="是否覆盖现有文件？"

    @end
    """
###########################
有提示以下错误
![image](https://github.com/zimolab/PyGUIAdapter/assets/35285952/3645da93-7d95-48ac-8224-1d3ceae0abc3)

**Comment by zimolab** [comment]
看起来你似乎是在交互环境下运行的代码而不是直接运行文件(python create_file_demo2.py)？看起来__uprint底层的C++(Qt)对象在调用set_print_destination()前就被delete了，但问题是__uprint这个QObject并没有parent，在代码中也没有显示地调用deleteLater()，可能在Jupyter Notebook这样的运行环境中不支持长时间维护C++对象。而通过直接运行文件的方式，并没有复现你的问题。所以我建议你直接运行文件试一下。另外，建议你新建一个虚拟环境并安装PyGUIAdapter最新版进行测试，毕竟不清楚你当前的python环境下是否存在其他冲突的包。

最后，由于你后面提的问题属于另一个方面的话题，所以此issue我先关闭，若后续再有问题欢迎另开issue进行讨论。
